### PR TITLE
Converted the Exceptional-PHP library into a custom CI library. 

### PR DESCRIPTION
**Pull request by wiiiimm**
- moved library configurations into the CI config file (config.php)
- wrapped static functions into public functions
- can be used in autoload.php for autoloading
- auto populate the Controller and Action information (no need to make
  Exceptional::$controller and Exceptional::$action calls now, all
  populated by the CI system)
- modified the documentations in README

### CODE REVIEW

**Comment by wiiiimm** [comment]
I am new to Git and GitHub so I am not sure what I should to regarding making a new branch that will work in CI framework. I guess I will start by sending you a pull request first?

**Comment by ankane** [comment]
Hey William, I'm opposed to adding any framework-specific support without a large demand. You may want to rename your project to something like `exceptional-php-codeigniter` and merge your changes to master so CodeIgniter developers can easily use your contributions.

**Comment by wiiiimm** [comment]
is there a way to rename the project but yet have it pull updates from your original branch?

**Comment by ankane** [comment]
Yes. To pull the latest changes, run:

``` sh
# First time only
git remote add ankane git@github.com:ankane/exceptional-php.git

git pull ankane master
```

If you keep all the CodeIgniter-specific code in a separate file, you'll run into less conflicts merging.

**Pull request closed without merging**
