### PR TITLE
Swapped require with require_once in all instances

### PR DESCRIPTION
**Pull request by snikch**
Since our test harness builds up and tears down our entire application context multiple times in a test, exceptional was requiring the same files multiple times and throwing 'cannot redeclare xx' exceptions. Now it will only load the file once.

### CODE REVIEW

**Comment by ankane** [comment]
Does the issue occur if you use `require_once` when including `exceptional.php`?

**Comment by snikch** [comment]
Yup, I'm using `require_once` however each time our Application Context is torn down it's triggering the shutdown function `Exceptional::shutdown` which in turn calls `require` on the two files it needs. I guess it's an edge case, but there's no problem with it using `require_once` rather than `require`.

**Comment by snikch** [comment]
Quick solution would be for me not to set up Exceptional during testing, but that's slightly harder :P

**Comment by ankane** [comment]
Cool, pull request accepted.  Thanks!

**Pull request merged**
