### PR TITLE
Feature to send custom parameters

### PR DESCRIPTION
**Pull request by jrbasso**
Sometimes the parameters have confidential information (like credit cards and password) and it is not nice to send to getexceptional.
We put this configuration and then you can set what will be sent. By default, it keep sending the GET and POST variables.

### CODE REVIEW

**Comment by ankane** [comment]
Hey Juan,

Exceptional definitely shouldn't be getting confidential information. I think the best way would be to pass a list of parameter names to filter.

``` php
$filter = array("password", "credit_card_number");
Exceptional::filter_parameters($filter);
```

Your thoughts?

**Comment by jrbasso** [comment]
The problem to filter recursively when the parameters is a multidimensional array.

I can do a path to create the filter, but create the parameters that users can do a filter easily using unset() or they can put information about others things, like some details of the logged user.

**Comment by ankane** [comment]
Writing a recursive function to handle multidimensional arrays shouldn't be too difficult.

`Exceptional::context()` is meant for extra details, like info about the current user.  We should make it clear in the design for this feature that it's only for filtering parameters. Also, instead of deleting parameters, I think we should replace them with `[FILTERED]` so when you log into Exceptional, you can see which parameters were filtered vs. which parameters were never passed.

**Comment by jrbasso** [comment]
Right, I agree. I will rewrite the code the code to implement the filter_parameters with multidimensional arrays and open a new pull request. Thanks.

**Pull request closed without merging**
